# Generated by Django 3.2.3 on 2021-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('primary_contact_number', models.CharField(blank=True, max_length=40, null=True)),
                ('secondary_contact_number', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('icu_beds', models.IntegerField(default=0)),
                ('isolation_beds', models.IntegerField(default=0)),
            ],
        ),
    ]
